---
- name: Install code-server from .deb file
  vars:
    code_server_url: https://github.com/cdr/code-server/releases/download/v3.3.1/code-server_3.3.1_amd64.deb
  apt:
    deb: "{{ code_server_url }}"

- name: Ensure code-server is enabled
  become_user: ubuntu
  systemd:
    name: code-server
    enabled: true
    state: started
    daemon_reload: true
    scope: user
