---
# https://docs.docker.com/engine/install/ubuntu/

- name: Install packages to allow apt to use a repository over HTTPS
  become: true
  apt:
    name: "{{ docker_prerequisite_packages }}"
    state: present
    update_cache: true
  vars:
    docker_prerequisite_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker’s official GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add apt repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install Docker engine
  become: true
  apt:
    name: "{{ docker_packages }}"
    state: present
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Ensure docker service is enabled
  become: true
  systemd:
    name: docker
    state: started
    enabled: true

- name: Install docker-compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: +x

- name: Install docker-py
  become: true
  pip:
    name: docker-py
