---
name: dev-env.terraform.cd

on:
  release:
    types:
      - published

env:
  tf_version: 0.12.24
  tf_working_dir: ./dev-env/terraform
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  STAGE: prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}
      - name: Run terraform init
        working-directory: ${{ env.tf_working_dir }}
        run: terraform init
      - name: Switch workspace
        working-directory: ${{ env.tf_working_dir }}
        run: terraform workspace select ${{ prod }}
      - name: Run terraform apply
        working-directory: ${{ env.tf_working_dir }}
        run: terraform apply -var-file vars/prod.tfvars -input=false -auto-approve
