---
name: dev-env.terraform.ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  tf_version: 0.12.14
  tf_working_dir: dev-env/terraform

jobs:
  tf-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
      - name: terraform validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
      # - name: terraform plan
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: ${{ env.tf_version }}
      #     tf_actions_subcommand: 'plan'
      #     tf_actions_working_dir: ${{ env.tf_working_dir }}
      #     args: --var-file vars/prod.tfvars
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tflint
        run: docker run -v `pwd`/dev-env/terraform:/data:ro wata727/tflint:0.15.5 --var-file=vars/prod.tfvars
