---
name: dev-env.ci

on:
  push:
    branches:
      - '*'

env:
  packer_working_dir: dev-env/packer
  tf_working_dir: dev-env/terraform

jobs:
  packer-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run packer validate
        working-directory: ${{ env.packer_working_dir }}
        run: docker run -v `pwd`:/mnt --workdir /mnt hashicorp/packer:light validate /mnt/instance.json

  tflint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.tf_working_dir }}
    steps:
      - uses: actions/checkout@v2

      - name: Run tflint for test
        run: docker run -v `pwd`:/data:ro wata727/tflint:latest --var-file=vars/test.tfvars

      - name: Run tflint for prod
        run: docker run -v `pwd`:/data:ro wata727/tflint:latest --var-file=vars/prod.tfvars
