---
name: dev-env.terraform.ci-pr

on:
  pull_request:
    branches:
      - master
    paths:
      - 'dev-env/terraform/**'
  push:
    branches:
      - master

env:
  tf_version: 0.12.24
  tf_working_dir: ./dev-env/terraform
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-ut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
      - name: terraform validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
      - name: terraform plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
          args: -var-file vars/prod.tfvars -input=false
  terratest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Download Go Modules
        working-directory: dev-env/terraform/tests
        run: go mod download
      - name: Run Go Tests
        working-directory: dev-env/terraform/tests
        run: go test -v -timeout 30m
