---
name: dev-env.terraform.ci

on:
  push:
    branches:
      - '*'
    paths:
      - 'dev-env/terraform/**'

env:
  tf_working_dir: dev-env/terraform

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tflint
        run: docker run -v `pwd`${{ env.tf_working_dir }}:/data:ro wata727/tflint:latest --var-file=vars/prod.tfvars
