---
name: dev-env.terraform.cd

on:
  release:
    types:
      - published

env:
  tf_version: 0.12.25
  tf_working_dir: dev-env/terraform
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    needs: create-ami
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.tf_working_dir }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Run terraform init
        run: terraform init

      - name: Switch workspace to prod
        run: terraform workspace select prod

      - name: Run terraform apply for prod
        run: terraform apply -var-file vars/prod.tfvars -input=false -auto-approve
