---
name: dev-env.packer.cd

on:
  release:
    types:
      - published
    paths:
      - 'dev-env/packer/**'

env:
  packer_working_dir: dev-env/packer
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  create-ami:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create AMI
        run: docker run -v `pwd`:/mnt --workdir /mnt -e AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }} -e AWS_DEFAULT_REGION=ap-northeast-1 hashicorp/packer:light build -force /mnt/instance.json
