---
name: dev-env.terraform.ci

on: push

env:
  tf_version: 0.12.14
  tf_working_dir: dev-env/terraform

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tflint
        run: docker run -v `pwd`/dev-env/terraform:/data:ro wata727/tflint:0.15.5 --var-file=vars/prod.tfvars
