---
name: dev-env.terraform.ci-pr

on:
  pull_request:
    branches:
      - master
    paths:
      - 'dev-env/terraform/**'
  push:
    branches:
      - master

env:
  tf_version: 0.12.24
  tf_working_dir: ./dev-env/terraform
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-ut:
    runs-on: ubuntu-latest
    env:
      STAGE: prod
    steps:
      - uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}
      - name: Run terraform init
        working-directory: ${{ env.tf_working_dir }}
        run: terraform init
      - name: Run terraform validate
        working-directory: ${{ env.tf_working_dir }}
        run: terraform validate
      - name: Run terraform plan
        working-directory: ${{ env.tf_working_dir }}
        run: terraform plan -var-file vars/prod.tfvars -input=false
  terratest:
    runs-on: ubuntu-latest
    env:
      STAGE: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Download Go Modules
        working-directory: dev-env/terraform/tests
        run: go mod download
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        working-directory: dev-env/terraform
        run: terraform init
      - name: Setup awscli
        uses: chrislennon/action-aws-cli@v1.1
      - name: Run Go Tests
        working-directory: dev-env/terraform/tests
        run: go test -v -timeout 30m
